apiVersion: v1
kind: Secret
metadata:
  name: senaite-app-secrets
  namespace: tenant-lab01
type: Opaque
stringData:
  SENAITE_ADMIN_USER: "admin"
  SENAITE_ADMIN_PASSWORD: "qo)~AXG>>mpBU8Bw%A.8n7hMX6"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USER: "smtp-user"
  SMTP_PASSWORD: "4RtXA+xHW9MDc%e0_GPsD?vFL*"
