apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: senaite-web-backendconfig
  namespace: tenant-lab01
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 8080
  # Optional: add your Cloud Armor policy name here after creation
  # securityPolicy:
  #   name: senaite-edge-policy
